CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE event (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL,
  image_url VARCHAR(1024) NOT NULL,
  event_url VARCHAR(1024) NOT NULL,
  date TIMESTAMP NOT NULL,
  remote BOOLEAN NOT NULL
);
